--Number of users hear each artist by below code:
SELECT E.ARTIST_NAME, S.ARTIST_ID,
ARTIST_LOCATION, ARTIST_LATITUDE,
ARTIST_LONGITUDE, COUNT(E.USER_ID) OVER(PARTITION BY E.ARTIST_NAME) USERS_NUMBER

FROM Events E, songs S
WHERE E.ARTIST_NAME = S.ARTIST_NAME

--Now we want to order them, and let's remove duplicates by below code
SELECT DISTINCT* FROM
(SELECT E.ARTIST_NAME, S.ARTIST_ID, ARTIST_LOCATION, ARTIST_LATITUDE, ARTIST_LONGITUDE,
COUNT(E.USER_ID) OVER(PARTITION BY E.ARTIST_NAME) USERS_NUMBER
FROM Events E, songs S
WHERE E.ARTIST_NAME = S.ARTIST_NAME) USER_SUB_Q
ORDER BY USERS_NUMBER DESC;

--the order of artists with their locations according to the number of users hear their songs
SELECT DISTINCT* FROM
(SELECT E.ARTIST_NAME, S.ARTIST_ID, ARTIST_LOCATION, ARTIST_LATITUDE, ARTIST_LONGITUDE,
COUNT(E.ARTIST_NAME) OVER(PARTITION BY E.ARTIST_NAME) USERS_NUMBER

FROM Events E, songs S
WHERE E.ARTIST_NAME = S.ARTIST_NAME) USER_SUB_Q
ORDER BY USERS_NUMBER DESC;

